language: ruby
cache: bundler
rvm:
  - 1.9.3
  - 2.1.0
script:
  - bundle exec rake proof_sitedir
# whitelist
branches:
  only:
    - master
matrix:
  fast_finish: true
  allow_failures:
    - rvm: 2.1.0
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
