# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
domain: moutons.github.io
author: Shaun Mouton
email: sdmouton@devops.christmas
title: Shaun Mouton

description: > # this means to ignore newlines until "baseurl:"
  Everybody's talkin bout that new sound, funny, but it's still rock
  and roll to me.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://moutons.github.io" # the base hostname & protocol for your site
twitter_username: sdmouton
github_username:  moutons

permalink: /articles/:title
exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - README.md
  - vendor

# Build settings
markdown: kramdown
