google_analytics_id: UA-45936912-1

# For Atom Feed
domain: www.sdm.me
author: Shaun Mouton
email: shaun@sdm.me
title: Shaun Mouton

# Standard Jekyll configs
permalink: /articles/:title
exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - README.md
  - vendor
markdown: rdiscount
# github:
#  username:
# disqus:
#  id:
