#!/usr/bin/env bash
set -e # halt script on error

npm install -g write-good

write-good ./_posts/* --so --thereIs --cliches --weasel

bundle exec jekyll build
bundle exec htmlproofer ./_site --allow-hash-href
